apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vpodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: bin5988/vprofile:app_v1
          ports:
            - name: vproapp-port 
              containerPort: 8080
      # if have dependencies pod, use initContainers for checking these pods
      # check db and memcached pods, make sure these pods run up first then run vproapp
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh','-c','until nslookup vprodb; do echo waiting for mydb; sleep; 2; done']
        - name: init-memcache
          image: busybox
          command: ['sh','-c','until nslookup vprocache01; do echo waiting for mydb; sleep; 2; done']
