apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 8090
      nodePort: 30001
      protocol: TCP
  selector:
    app: nginx
